# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cec67c0401fcd3061c30b884ae8acb79fdcd8370c50c89028ea9e96f72ea611f3a166bf8738c0afcfe8df56169b4c198ccdd64cdeb69ca364cf7c6102b142f22

test:
  secret_key_base: 8f9251b61fe17e127da60e49c5550ebf7ee9aec8c9515a1b499a0dfb881f59c93a5346722d614438a805511f49b45a7c8a84eeae85d27fc7bc3e2d8a15c5e00a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
